### ISSUE TITLE
EN-FR bicleaner error : KeyError: 'good_examples'

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bicleaner-data#1]
Hi,
I'm running in a docker bitextor. I try to use bicleaner so I downloaded EN-FR release and updated my bitextor conf.
When I try to run it I got this error :
```
slang=$(egrep "source_lang" /home/bicleaner/en-fr/en-fr.yaml | cut -d " " -f 2)
        if [ "$slang" == "en" ]; then
          xzcat -T 0 -f /home/transient/bbtsoftware/hunalign.bifixer.xz |
          /usr/bin/time -v /opt/bitextor/preprocess/bin/cache -k 6 python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /home/bicleaner/en-fr/en-fr.yaml |
          paste <(xzcat -T 0 /home/transient/bbtsoftware/hunalign.bifixer.xz) - |
          xz -T 0 > /home/transient/bbtsoftware/hunalign.bicleaner.scores.xz
        else
          xzcat -T 0 -f /home/transient/bbtsoftware/hunalign.bifixer.xz |
          awk ' BEGIN {FS="	"; OFS="	"} { t = $3; $3 = $4; $4 = t; print;}' |
          /usr/bin/time -v /opt/bitextor/preprocess/bin/cache -k 6 python3  /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /home/bicleaner/en-fr/en-fr.yaml |
          paste <(xzcat -T 0 /home/transient/bbtsoftware/hunalign.bifixer.xz) - |
          xz -T 0 > /home/transient/bbtsoftware/hunalign.bicleaner.scores.xz
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
When I try this by hand I got the following error message : 
```
File "/opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py", line 135, in initialization
    args.good_examples = metadata_yaml["good_examples"]
KeyError: 'good_examples'
Command terminated by signal 13
```

Do you have any solution ?

Regards

**Comment by mbanon** [comment]
Hi @jgcb00 , thanks for your comment.

It seems that the Docker image does not have the latest Bicleaner, so the current latest language packs for Bicleaner are not working.

Please try downoading the former version (https://github.com/bitextor/bicleaner-data/releases/tag/v1.3), and let us know if that works for you.

-Marta

**Comment by jgcb00** [comment]
Hi @mbanon ,
Thanks for your quick reply, indeed that was the issue, works fine now. Do you plan to update your docker image ? 

Thanks a lot
-Jean-Gabriel

**Comment by lpla** [comment]
We expect to update the docker image once we release the next Bitextor release. Currently, Docker image contains master branch code.

In case you are interested, some of the next Bitextor release features are being merged into 'snake_performance' branch, so if you are in a hurry to use them, you can checkout that branch and install their new dependencies as specified in the updated README in that branch.

**Comment by jgcb00** [comment]
Ok thanks a lot for your great work ! 
Good luck and looking forward for new version !
